---
deployment:
  tasks:
    - export DEPLOYPATH=/home/binnetbi/public_html/
    - test -f site/index.html
    - test -d "$DEPLOYPATH"
    - /bin/rsync -av --delete --exclude='.well-known/' --exclude='cgi-bin/' --exclude='.htaccess' --exclude='.user.ini' --exclude='php.ini' site/ "$DEPLOYPATH"
